apiVersion: v1
kind: Service
metadata:
  name: bitplay-frontend-service
  labels:
    app: bitplay-frontend
spec:
  type: NodePort
  selector:
    app: bitplay-frontend
  ports:
    - port: 8080
      targetPort: 8080
